"use strict"
// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('my new', function () {
    this.timeout(30000)
    let driver
    let vars
    beforeEach(async function () {
        driver = await new Builder().forBrowser('chrome').build()
        vars = {}
    })
    afterEach(async function () {
        await driver.quit();
    })
    it('my new', async function () {
        await driver.get("https://www.bing.com/")
        await driver.manage().window().setRect(695, 728)
        await driver.findElement(By.id("sb_form_q")).click()
        await driver.findElement(By.id("sb_form_q")).sendKeys("hello world")
        await driver.findElement(By.id("sb_form_q")).sendKeys(Key.ENTER)
        assert(await driver.getTitle() == "hello world - Bing")
        {
            const element = await driver.findElement(By.linkText("Hello World - MyAnimeList.net"))
            const locator = `option[@value='${await element.getAttribute("value")}']`
            const selectedText = await element.findElement(By.xpath(locator)).getText()
            assert(selectedText == "Hello World - MyAnimeList.net")
        }
        {
            const elements = await driver.findElements(By.linkText("Hello World - MyAnimeList.net"))
            assert(elements.length)
        }
    })
})
