"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.playersDb = exports.gamesDb = void 0;
const gamesRedisDb_1 = require("./gamesRedisDb");
const palyersmongoDb_1 = require("./palyersmongoDb");
const dotenv_1 = require("dotenv");
const util_1 = require("util");
const makeMongoDb_1 = require("./helpers/makeMongoDb");
const makeRedisDb_1 = require("./helpers/makeRedisDb");
dotenv_1.config();
const gamesDbNumber = process.env.GAMES_DB_NUMBER;
const gamesDb = gamesRedisDb_1.default(makeRedisDb_1.default(gamesDbNumber), util_1.promisify);
exports.gamesDb = gamesDb;
const playersDb = palyersmongoDb_1.default(makeMongoDb_1.default);
exports.playersDb = playersDb;
